"""
openfoam/ahmed_case_generator.py

Generates complete OpenFOAM simpleFoam cases for Ahmed body geometries.

Takes geometry parameters from ParaKoop inverse design output and writes:
  case_dir/
    0/             → U, p, nut, k, omega
    constant/      → polyMesh/blockMeshDict, transportProperties, turbulenceProperties
    system/        → controlDict, fvSolution, fvSchemes, decomposeParDict

Solver: simpleFoam  (steady incompressible RANS, k-ω SST)
Reference: Lienhart et al. DGLR/SAE-Paper 2000-01-0484 — standard Ahmed body protocol
           Wind tunnel speed U∞ = 40 m/s, Re ≈ 2.8×10⁶ based on body length

Ahmed body coordinate system (metres):
  x  : streamwise (+ downstream)
  y  : lateral    (+ right)
  z  : vertical   (+ up)
  Body sits on floor z=0, centred at y=0, nose at x=0.

Usage
-----
    from openfoam.ahmed_case_generator import generate_ahmed_case

    generate_ahmed_case(
        case_dir   = "openfoam/cases/slant25",
        length_m   = 1.044,
        height_m   = 0.288,
        width_m    = 0.389,
        slant_deg  = 25.0,
        ground_clr = 0.050,
    )

Then in a terminal with OpenFOAM loaded:
    cd openfoam/cases/slant25
    blockMesh
    simpleFoam
    foamCalc mag U          # optional post-processing
"""

from __future__ import annotations

import json
import math
import os
from pathlib import Path
from typing import Optional


# ── Wind tunnel physics ────────────────────────────────────────────────────
U_INF    = 40.0        # m/s   freestream velocity
RHO      = 1.225       # kg/m³ air density at 20°C
NU       = 1.516e-5    # m²/s  kinematic viscosity at 20°C
A_SOUND  = 343.0       # m/s   speed of sound

# Turbulence inlet conditions (5% intensity, viscosity ratio 10)
TI       = 0.05
NU_RATIO = 10.0
K_INLET  = 1.5 * (U_INF * TI) ** 2
EPS_INF  = K_INLET * math.sqrt(K_INLET) * 0.09 ** 0.25   # estimate for omega inlet
OMEGA_INLET = math.sqrt(K_INLET) / (0.09 ** 0.25 * 0.001) if True else 100.0

# Frontal radius (standard AhmedML): rounded nose, fixed at ~100mm
NOSE_RADIUS_M = 0.100

# Side slant angle (fixed in standard Ahmed body)
SIDE_SLANT_DEG = 20.0

# Domain size multipliers (body-lengths)
DOMAIN_X_UPSTREAM  = 5.0   # lengths upstream of nose
DOMAIN_X_DOWNSTREAM= 12.0  # lengths downstream of base
DOMAIN_Y_HALF      = 5.0   # half-width
DOMAIN_Z_TOP       = 6.0   # heights above ground

_HEADER = """\
/*--------------------------------*- C++ -*----------------------------------*\\
| OpenFOAM Ahmed body case — generated by ParaKoop/openfoam/ahmed_case_generator.py |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    location    "{loc}";
    object      {obj};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
"""


def _header(cls: str, loc: str, obj: str) -> str:
    return _HEADER.format(cls=cls, loc=loc, obj=obj)


# ══════════════════════════════════════════════════════════════════════════
# Geometry helpers
# ══════════════════════════════════════════════════════════════════════════

def ahmed_body_points(L: float, H: float, W: float,
                      slant_deg: float, grnd: float,
                      nose_r: float = NOSE_RADIUS_M,
                      side_slant_deg: float = SIDE_SLANT_DEG) -> dict:
    """
    Returns key geometry dimensions of the Ahmed body in metres.

    Coordinate origin: front-bottom-centre (nose tip at (0, 0, grnd)).
    """
    slant_rad      = math.radians(slant_deg)
    side_slant_rad = math.radians(side_slant_deg)

    # Rear slant: projects backward and upward
    slant_h = H * math.sin(slant_rad)            # vertical drop of slant
    slant_x = slant_h / math.tan(slant_rad)      # = H * cos(slant_rad)
    slant_x = H * math.cos(slant_rad)

    # Side taper: the rear bottom corners taper inward
    side_inset = H * math.tan(side_slant_rad)    # lateral inset at rear base

    return {
        'L': L, 'H': H, 'W': W, 'grnd': grnd,
        'nose_r': nose_r, 'slant_deg': slant_deg,
        'slant_x': slant_x, 'slant_h': slant_h,
        'side_inset': side_inset,
        'body_top_z':  grnd + H,           # z at roof
        'body_base_z': grnd,               # z at underbody
        'base_x': L - slant_x,            # x where rear slant starts
        'slant_top_z': grnd + H,          # rear slant top (= roof height)
        'slant_bot_z': grnd + H - slant_h, # rear slant bottom
    }


def _re(L: float) -> float:
    return U_INF * L / NU


# ══════════════════════════════════════════════════════════════════════════
# OpenFOAM file writers
# ══════════════════════════════════════════════════════════════════════════

def _write_block_mesh_dict(geo: dict, out_dir: Path) -> None:
    """
    blockMeshDict for the outer wind-tunnel domain.
    Mesh cells: uniform hex with ~50mm base cell size.
    Refinement done in snappyHexMesh (see snappy_hex_mesh_dict).
    """
    L = geo['L']
    x0 = -DOMAIN_X_UPSTREAM  * L
    x1 =  DOMAIN_X_DOWNSTREAM * L
    y0 = -DOMAIN_Y_HALF      * geo['W'] / 2
    y1 =  DOMAIN_Y_HALF      * geo['W'] / 2
    z0 =  0.0
    z1 =  DOMAIN_Z_TOP       * geo['H']

    dx, dy, dz = (x1 - x0), (y1 - y0), z1
    nx = max(20, int(dx / (L / 10)))
    ny = max(10, int(dy / (geo['W'] / 5)))
    nz = max(10, int(dz / (geo['H'] / 4)))

    content = _header('dictionary', 'constant/polyMesh', 'blockMeshDict') + f"""
scale 1.0;

vertices
(
    ({x0:.4f} {y0:.4f} {z0:.4f})  // 0
    ({x1:.4f} {y0:.4f} {z0:.4f})  // 1
    ({x1:.4f} {y1:.4f} {z0:.4f})  // 2
    ({x0:.4f} {y1:.4f} {z0:.4f})  // 3
    ({x0:.4f} {y0:.4f} {z1:.4f})  // 4
    ({x1:.4f} {y0:.4f} {z1:.4f})  // 5
    ({x1:.4f} {y1:.4f} {z1:.4f})  // 6
    ({x0:.4f} {y1:.4f} {z1:.4f})  // 7
);

blocks
(
    hex (0 1 2 3 4 5 6 7)
    ({nx} {ny} {nz})
    simpleGrading (1 1 1)
);

boundary
(
    inlet
    {{
        type patch;
        faces ((0 4 7 3));
    }}
    outlet
    {{
        type patch;
        faces ((1 2 6 5));
    }}
    top
    {{
        type symmetryPlane;
        faces ((4 5 6 7));
    }}
    sides
    {{
        type symmetryPlane;
        faces ((0 1 5 4) (3 7 6 2));
    }}
    ground
    {{
        type wall;
        faces ((0 3 2 1));
    }}
);
"""
    (out_dir / 'constant' / 'polyMesh' / 'blockMeshDict').write_text(content)


def _write_snappy_hex_mesh(geo: dict, out_dir: Path) -> None:
    """
    snappyHexMeshDict — refines the mesh around and inside the Ahmed body.
    Assumes ahmed_body.stl is in constant/triSurface/.
    """
    content = _header('dictionary', 'system', 'snappyHexMeshDict') + """
castellatedMesh true;
snap            true;
addLayers       true;

mergeTolerance  1e-6;

geometry
{
    ahmed_body
    {
        type triSurfaceMesh;
        file "ahmed_body.stl";
    }
    refinementBox
    {
        type searchableBox;
        min  (-0.1 -0.3 0.0);
        max  ( 2.5  0.3 0.5);
    }
}

castellatedMeshControls
{
    maxLocalCells        1000000;
    maxGlobalCells       5000000;
    minRefinementCells   10;
    nCellsBetweenLevels  3;

    features ( );

    refinementSurfaces
    {
        ahmed_body
        {
            level (3 4);
            patchInfo { type wall; }
        }
    }

    refinementRegions
    {
        refinementBox { mode inside; levels ((1 1)); }
        ahmed_body    { mode distance; levels ((0.05 3) (0.15 2) (0.5 1)); }
    }

    resolveFeatureAngle 30;
    locationInMesh (""" + f"{-geo['L']*0.5:.4f} 0.05 {geo['H']*0.5 + 0.05:.4f}" + """);  // offset from cell faces
    allowFreeStandingZoneFaces true;
}

snapControls
{
    nSmoothPatch    3;
    tolerance       2.0;
    nSolveIter      30;
    nRelaxIter      5;
}

addLayersControls
{
    relativeSizes       true;
    layers
    {
        ahmed_body { nSurfaceLayers 5; }
        ground     { nSurfaceLayers 3; }
    }
    expansionRatio          1.2;
    finalLayerThickness     0.3;
    minThickness            0.1;
    nGrow                   0;
    featureAngle            60;
    nRelaxIter              3;
    nSmoothSurfaceNormals   1;
    nSmoothNormals          3;
    nSmoothThickness        10;
    maxFaceThicknessRatio   0.5;
    maxThicknessToMedialRatio 0.3;
    minMedialAxisAngle      90;
    nBufferCellsNoExtrude   0;
    nLayerIter              50;
}

meshQualityControls
{
    maxNonOrtho         65;
    maxBoundarySkewness 20;
    maxInternalSkewness 4;
    maxConcave          80;
    minFlatness         0.5;
    minVol              1e-13;
    minTetQuality       1e-30;
    minArea             -1;
    minTwist            0.02;
    minDeterminant      0.001;
    minFaceWeight       0.05;
    minVolRatio         0.01;
    minTriangleTwist    -1;
    nSmoothScale        4;
    errorReduction      0.75;
}
"""
    (out_dir / 'system' / 'snappyHexMeshDict').write_text(content)


def _write_U(geo: dict, out_dir: Path) -> None:
    content = _header('volVectorField', '"0"', 'U') + f"""
dimensions  [0 1 -1 0 0 0 0];

internalField  uniform ({U_INF} 0 0);

boundaryField
{{
    inlet       {{ type fixedValue;       value uniform ({U_INF} 0 0); }}
    outlet      {{ type zeroGradient; }}
    ground      {{ type noSlip; }}
    top         {{ type symmetryPlane; }}
    sides       {{ type symmetryPlane; }}
    ahmed_body  {{ type noSlip; }}
}}
"""
    (out_dir / '0' / 'U').write_text(content)


def _write_p(out_dir: Path) -> None:
    content = _header('volScalarField', '"0"', 'p') + """
dimensions  [0 2 -2 0 0 0 0];

internalField  uniform 0;

boundaryField
{
    inlet       { type zeroGradient; }
    outlet      { type fixedValue;   value uniform 0; }
    ground      { type zeroGradient; }
    top         { type symmetryPlane; }
    sides       { type symmetryPlane; }
    ahmed_body  { type zeroGradient; }
}
"""
    (out_dir / '0' / 'p').write_text(content)


def _write_nut(out_dir: Path) -> None:
    content = _header('volScalarField', '"0"', 'nut') + f"""
dimensions  [0 2 -1 0 0 0 0];

internalField  uniform {NU * NU_RATIO:.3e};

boundaryField
{{
    inlet       {{ type calculated;   value uniform {NU * NU_RATIO:.3e}; }}
    outlet      {{ type calculated;   value uniform {NU * NU_RATIO:.3e}; }}
    ground      {{ type nutkWallFunction; value uniform 0; }}
    top         {{ type symmetryPlane; }}
    sides       {{ type symmetryPlane; }}
    ahmed_body  {{ type nutkWallFunction; value uniform 0; }}
}}
"""
    (out_dir / '0' / 'nut').write_text(content)


def _write_k(out_dir: Path) -> None:
    content = _header('volScalarField', '"0"', 'k') + f"""
dimensions  [0 2 -2 0 0 0 0];

internalField  uniform {K_INLET:.4e};

boundaryField
{{
    inlet       {{ type fixedValue;      value uniform {K_INLET:.4e}; }}
    outlet      {{ type zeroGradient; }}
    ground      {{ type kqRWallFunction; value uniform {K_INLET:.4e}; }}
    top         {{ type symmetryPlane; }}
    sides       {{ type symmetryPlane; }}
    ahmed_body  {{ type kqRWallFunction; value uniform {K_INLET:.4e}; }}
}}
"""
    (out_dir / '0' / 'k').write_text(content)


def _write_omega(out_dir: Path) -> None:
    omega_wall = 10.0 * 6 * NU / (0.075 * (0.005 ** 2))   # y+ ~1 estimate
    content = _header('volScalarField', '"0"', 'omega') + f"""
dimensions  [0 0 -1 0 0 0 0];

internalField  uniform {OMEGA_INLET:.2f};

boundaryField
{{
    inlet       {{ type fixedValue;         value uniform {OMEGA_INLET:.2f}; }}
    outlet      {{ type zeroGradient; }}
    ground      {{ type omegaWallFunction;  value uniform {omega_wall:.1f}; }}
    top         {{ type symmetryPlane; }}
    sides       {{ type symmetryPlane; }}
    ahmed_body  {{ type omegaWallFunction;  value uniform {omega_wall:.1f}; }}
}}
"""
    (out_dir / '0' / 'omega').write_text(content)


def _write_transport_properties(out_dir: Path) -> None:
    content = _header('dictionary', 'constant', 'transportProperties') + f"""
transportModel  Newtonian;
nu              {NU:.4e};
"""
    (out_dir / 'constant' / 'transportProperties').write_text(content)


def _write_turbulence_properties(out_dir: Path) -> None:
    content = _header('dictionary', 'constant', 'turbulenceProperties') + """
simulationType  RAS;

RAS
{
    RASModel    kOmegaSST;
    turbulence  on;
    printCoeffs on;
}
"""
    (out_dir / 'constant' / 'turbulenceProperties').write_text(content)


def _write_control_dict(geo: dict, out_dir: Path, n_iter: int = 1000) -> None:
    L = geo['L']
    content = _header('dictionary', 'system', 'controlDict') + f"""
application     simpleFoam;
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         {n_iter};
deltaT          1;
writeControl    timeStep;
writeInterval   100;
purgeWrite      3;
writeFormat     ascii;
writePrecision  6;
writeCompression off;
timeFormat      general;
timePrecision   6;
runTimeModifiable true;

functions
{{
    forceCoeffs
    {{
        type            forceCoeffs;
        libs            ("libforces.so");
        writeControl    timeStep;
        writeInterval   10;
        log             true;
        patches         (ahmed_body);
        rho             rhoInf;
        rhoInf          1.225;
        liftDir         (0 0 1);
        dragDir         (1 0 0);
        CofR            (0 0 0);
        pitchAxis       (0 1 0);
        magUInf         {U_INF};
        lRef            {L:.4f};
        Aref            {geo['H'] * geo['W']:.6f};
    }}
}}
"""
    (out_dir / 'system' / 'controlDict').write_text(content)


def _write_fv_schemes(out_dir: Path) -> None:
    content = _header('dictionary', 'system', 'fvSchemes') + """
ddtSchemes    { default steadyState; }
gradSchemes   { default Gauss linear; }
divSchemes
{
    default         none;
    div(phi,U)      Gauss linearUpwind grad(U);
    div(phi,k)      Gauss upwind;
    div(phi,omega)  Gauss upwind;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}
laplacianSchemes { default Gauss linear corrected; }
interpolationSchemes { default linear; }
snGradSchemes    { default corrected; }
wallDist         { method meshWave; }
"""
    (out_dir / 'system' / 'fvSchemes').write_text(content)


def _write_fv_solution(out_dir: Path) -> None:
    content = _header('dictionary', 'system', 'fvSolution') + """
solvers
{
    p     { solver PCG; preconditioner DIC; tolerance 1e-7; relTol 0.01; }
    U     { solver smoothSolver; smoother symGaussSeidel; tolerance 1e-8; relTol 0.1; }
    k     { solver smoothSolver; smoother symGaussSeidel; tolerance 1e-8; relTol 0.1; }
    omega { solver smoothSolver; smoother symGaussSeidel; tolerance 1e-8; relTol 0.1; }
}

SIMPLE
{
    nNonOrthogonalCorrectors 0;
    consistent yes;
    residualControl
    {
        p       1e-5;
        U       1e-5;
        "(k|omega)" 1e-5;
    }
}

relaxationFactors
{
    fields  { p 0.3; }
    equations { U 0.7; k 0.7; omega 0.7; }
}
"""
    (out_dir / 'system' / 'fvSolution').write_text(content)


def _write_decompose_par(out_dir: Path, n_procs: int = 4) -> None:
    content = _header('dictionary', 'system', 'decomposeParDict') + f"""
numberOfSubdomains {n_procs};
method           scotch;
"""
    (out_dir / 'system' / 'decomposeParDict').write_text(content)


def _write_run_script(case_dir: Path, geo: dict) -> None:
    """Allrun shell script."""
    re = _re(geo['L'])
    content = f"""#!/bin/bash
# ParaKoop Ahmed body validation case
# Geometry: L={geo['L']*1000:.0f}mm H={geo['H']*1000:.0f}mm W={geo['W']*1000:.0f}mm
#           slant={geo['slant_deg']:.1f}° ground={geo['ground_clr']*1000:.0f}mm
# Flow:     U∞={U_INF}m/s  Re={re:.2e}  ν={NU:.3e}m²/s
# Solver:   simpleFoam k-ω SST

cd "$(dirname "$0")"

# 1. Mesh the outer domain
blockMesh 2>&1 | tee log.blockMesh

# 2. Copy STL to constant/triSurface (generate ahmed_body.stl first)
mkdir -p constant/triSurface
[ -f ahmed_body.stl ] && cp ahmed_body.stl constant/triSurface/ || \\
    echo "WARNING: ahmed_body.stl not found — generate with generate_ahmed_stl.py first"

# 3. Surface feature extraction + snappy meshing
surfaceFeatureExtract  2>&1 | tee log.surfaceFeatureExtract
snappyHexMesh -overwrite 2>&1 | tee log.snappyHexMesh

# 4. Run simpleFoam
simpleFoam 2>&1 | tee log.simpleFoam

# 5. Extract Cd/Cl from force coefficients
grep "Cd" postProcessing/forceCoeffs/0/forceCoeffs.dat | tail -5
echo "---"
echo "ParaKoop predicted Cd: {geo.get('pk_cd_pred', 'N/A')}  Cl: {geo.get('pk_cl_pred', 'N/A')}"
"""
    (case_dir / 'Allrun').write_text(content)
    (case_dir / 'Allrun').chmod(0o755)


def _write_surface_feature_dict(out_dir: Path) -> None:
    content = _header('dictionary', 'system', 'surfaceFeatureExtractDict') + """
ahmed_body.stl
{
    extractionMethod    extractFromSurface;
    extractFromSurfaceCoeffs { includedAngle 150; }
    writeObj yes;
}
"""
    (out_dir / 'system' / 'surfaceFeatureExtractDict').write_text(content)


def _write_ahmed_stl(geo: dict, out_path: Path) -> None:
    """
    Generate a simplified Ahmed body STL (triangulated surfaces) in metres.

    This is an approximate geometry: straight sides with the slant at the
    correct angle. For high-fidelity runs, use CAD-generated STL.

    Surfaces: front_face, roof, underbody, rear_slant, rear_base,
              left_side, right_side + ground_clearance sides
    """
    L, H, W    = geo['L'], geo['H'], geo['W']
    grnd       = geo['ground_clr']
    slant_x    = geo['slant_x']
    slant_h    = geo['slant_h']
    body_top_z = grnd + H
    base_x     = L - slant_x   # x where rear slant starts
    side_in    = geo['side_inset']

    # Key x positions (all from nose)
    x_nose = 0.0
    x_cabin_start = 0.3 * L    # approximate cabin start (simplified)
    x_base  = base_x
    x_tail  = L

    # Half-width
    yw = W / 2.0

    triangles = []

    def tri(p1, p2, p3, normal=None):
        triangles.append((p1, p2, p3))

    def quad(p1, p2, p3, p4):
        # Two triangles from a quad (p1,p2,p3,p4 in order)
        tri(p1, p2, p3)
        tri(p1, p3, p4)

    # ── Underbody ────────────────────────────────────────────────────────
    quad((x_nose, -yw, grnd), (x_tail, -yw, grnd),
         (x_tail,  yw, grnd), (x_nose,  yw, grnd))

    # ── Roof ─────────────────────────────────────────────────────────────
    quad((x_nose, -yw, body_top_z), (x_base, -yw, body_top_z),
         (x_base,  yw, body_top_z), (x_nose,  yw, body_top_z))

    # ── Front face (vertical) ─────────────────────────────────────────────
    quad((x_nose, -yw, grnd), (x_nose,  yw, grnd),
         (x_nose,  yw, body_top_z), (x_nose, -yw, body_top_z))

    # ── Left side ─────────────────────────────────────────────────────────
    # Main body side (between nose and base)
    quad((x_nose, -yw, grnd), (x_nose, -yw, body_top_z),
         (x_base, -yw, body_top_z), (x_base, -yw, grnd))
    # Rear slant side (tapered by side_inset)
    z_slant_bot = body_top_z - slant_h
    quad((x_base, -yw, body_top_z), (x_tail, -(yw - side_in), z_slant_bot),
         (x_tail, -(yw - side_in), grnd), (x_base, -yw, grnd))

    # ── Right side (mirror) ───────────────────────────────────────────────
    quad((x_nose,  yw, grnd), (x_base,  yw, grnd),
         (x_base,  yw, body_top_z), (x_nose,  yw, body_top_z))
    quad((x_base,  yw, grnd), (x_tail,  (yw - side_in), grnd),
         (x_tail,  (yw - side_in), z_slant_bot), (x_base,  yw, body_top_z))

    # ── Rear slant ────────────────────────────────────────────────────────
    # From roof-base edge down to slant bottom
    quad((x_base, -yw, body_top_z), (x_base,  yw, body_top_z),
         (x_tail,  (yw - side_in), z_slant_bot),
         (x_tail, -(yw - side_in), z_slant_bot))

    # ── Rear base (vertical panel below slant bottom) ─────────────────────
    quad((x_tail, -(yw - side_in), grnd), (x_tail,  (yw - side_in), grnd),
         (x_tail,  (yw - side_in), z_slant_bot),
         (x_tail, -(yw - side_in), z_slant_bot))

    # ── Write ASCII STL ───────────────────────────────────────────────────
    lines = ["solid ahmed_body"]
    for p1, p2, p3 in triangles:
        # Compute face normal
        v1 = (p2[0]-p1[0], p2[1]-p1[1], p2[2]-p1[2])
        v2 = (p3[0]-p1[0], p3[1]-p1[1], p3[2]-p1[2])
        nx = v1[1]*v2[2] - v1[2]*v2[1]
        ny = v1[2]*v2[0] - v1[0]*v2[2]
        nz = v1[0]*v2[1] - v1[1]*v2[0]
        mag = math.sqrt(nx*nx + ny*ny + nz*nz) + 1e-15
        nx, ny, nz = nx/mag, ny/mag, nz/mag
        lines.append(f"  facet normal {nx:.6f} {ny:.6f} {nz:.6f}")
        lines.append("    outer loop")
        for p in (p1, p2, p3):
            lines.append(f"      vertex {p[0]:.6f} {p[1]:.6f} {p[2]:.6f}")
        lines.append("    endloop")
        lines.append("  endfacet")
    lines.append("endsolid ahmed_body")

    out_path.write_text("\n".join(lines))


# ══════════════════════════════════════════════════════════════════════════
# Public API
# ══════════════════════════════════════════════════════════════════════════

def generate_ahmed_case(
    case_dir:    str,
    length_m:    float,
    height_m:    float,
    width_m:     float,
    slant_deg:   float,
    ground_clr:  float = 0.050,
    n_iter:      int   = 1000,
    n_procs:     int   = 4,
    pk_cd_pred:  Optional[float] = None,
    pk_cl_pred:  Optional[float] = None,
) -> dict:
    """
    Write a complete OpenFOAM simpleFoam case for an Ahmed body.

    Parameters
    ----------
    case_dir   : output directory (created if needed)
    length_m   : body length in metres
    height_m   : body height in metres (ground clearance not included)
    width_m    : body width in metres
    slant_deg  : rear slant angle in degrees
    ground_clr : ground clearance in metres (default 50mm = 0.050)
    n_iter     : number of simpleFoam iterations (default 1000)
    n_procs    : MPI decomposition processors (default 4)
    pk_cd_pred : ParaKoop predicted Cd (annotated in Allrun script)
    pk_cl_pred : ParaKoop predicted Cl (annotated in Allrun script)

    Returns
    -------
    dict with geometry summary and file paths written
    """
    out = Path(case_dir)
    (out / '0').mkdir(parents=True, exist_ok=True)
    (out / 'constant' / 'polyMesh').mkdir(parents=True, exist_ok=True)
    (out / 'constant' / 'triSurface').mkdir(parents=True, exist_ok=True)
    (out / 'system').mkdir(parents=True, exist_ok=True)

    geo = ahmed_body_points(length_m, height_m, width_m, slant_deg, ground_clr)
    geo['ground_clr'] = ground_clr
    if pk_cd_pred is not None:
        geo['pk_cd_pred'] = pk_cd_pred
    if pk_cl_pred is not None:
        geo['pk_cl_pred'] = pk_cl_pred

    # Write all OpenFOAM dictionaries
    _write_block_mesh_dict(geo, out)
    _write_snappy_hex_mesh(geo, out)
    _write_U(geo, out)
    _write_p(out)
    _write_nut(out)
    _write_k(out)
    _write_omega(out)
    _write_transport_properties(out)
    _write_turbulence_properties(out)
    _write_control_dict(geo, out, n_iter)
    _write_fv_schemes(out)
    _write_fv_solution(out)
    _write_decompose_par(out, n_procs)
    _write_surface_feature_dict(out)

    # Generate Ahmed body STL
    stl_path = out / 'constant' / 'triSurface' / 'ahmed_body.stl'
    _write_ahmed_stl(geo, stl_path)

    # Write Allrun script
    _write_run_script(out, geo)

    # Write geometry summary JSON
    summary = {
        'length_mm':  length_m * 1000,
        'height_mm':  height_m * 1000,
        'width_mm':   width_m  * 1000,
        'slant_deg':  slant_deg,
        'ground_clr_mm': ground_clr * 1000,
        'Re':         _re(length_m),
        'U_inf_ms':   U_INF,
        'frontal_area_m2': height_m * width_m,
        'pk_cd_pred': pk_cd_pred,
        'pk_cl_pred': pk_cl_pred,
    }
    (out / 'parakoop_geometry.json').write_text(json.dumps(summary, indent=2))

    return {'case_dir': str(out), 'geo': geo, 'files_written': sorted(str(p) for p in out.rglob('*') if p.is_file())}


def generate_cases_from_inverse_design(
    results_json:  str,
    output_dir:    str = 'openfoam/cases',
    ref_length_m:  float = 0.900,
    ref_height_m:  float = 0.288,
    ref_width_m:   float = 0.389,
    ground_clr_m:  float = 0.050,
) -> list:
    """
    Generate OpenFOAM cases from inverse_suggest.py JSON output.

    Parameters
    ----------
    results_json : path to JSON saved by `inverse_suggest.py --json <path>`
    output_dir   : base directory for cases
    ref_length_m : reference body length in metres (AhmedML default ≈ 0.9m)
    ref_height_m : reference body height in metres (AhmedML default ≈ 0.288m)
    ref_width_m  : reference body width in metres  (AhmedML default ≈ 0.389m)

    Returns
    -------
    list of case directories written
    """
    with open(results_json) as f:
        results = json.load(f)

    if isinstance(results, dict):
        results = [results]

    cases = []
    for i, r in enumerate(results):
        ep = r.get('end_params', {})
        # Scale: use slant_deg from end_params if available
        slant_deg = ep.get('rear_slant_deg', 25.0)
        h_mm = ep.get('height_mm', ref_height_m * 1000)
        w_mm = ep.get('width_mm',  ref_width_m  * 1000)

        # Scale to AhmedML reference length (keep ratios)
        # end_params give DrivAerNet-scale mm; rescale by h_l_ratio
        theta_end = r.get('theta_end', [])
        if len(theta_end) >= 4:
            h_l_ratio = theta_end[3]
            h_m   = h_l_ratio * ref_length_m
            w_h_ratio = theta_end[4] if len(theta_end) >= 5 else 1.35
            w_m   = w_h_ratio * h_m
        else:
            h_m = ref_height_m
            w_m = ref_width_m

        label    = f"slant{slant_deg:.0f}_case{i+1:02d}"
        case_dir = os.path.join(output_dir, label)
        info     = generate_ahmed_case(
            case_dir   = case_dir,
            length_m   = ref_length_m,
            height_m   = h_m,
            width_m    = w_m,
            slant_deg  = slant_deg,
            ground_clr = ground_clr_m,
            pk_cd_pred = r.get('achieved_cd'),
            pk_cl_pred = r.get('achieved_cl'),
        )
        cases.append(case_dir)
        print(f"  [{i+1}] {label}  L={ref_length_m*1000:.0f}mm h={h_m*1000:.0f}mm "
              f"slant={slant_deg:.1f}°  → {case_dir}")

    return cases


# ── CLI ────────────────────────────────────────────────────────────────────
if __name__ == '__main__':
    import argparse
    pa = argparse.ArgumentParser(
        description='Generate OpenFOAM Ahmed body cases from ParaKoop inverse design')
    pa.add_argument('--slants', type=float, nargs='+',
                    default=[10.0, 17.5, 25.0, 35.0, 45.0],
                    help='Rear slant angles to generate cases for')
    pa.add_argument('--length', type=float, default=0.900, help='Body length (m)')
    pa.add_argument('--height', type=float, default=0.288, help='Body height (m)')
    pa.add_argument('--width',  type=float, default=0.389, help='Body width (m)')
    pa.add_argument('--ground', type=float, default=0.050, help='Ground clearance (m)')
    pa.add_argument('--out', default='openfoam/cases', help='Output directory')
    pa.add_argument('--from-json', default=None, help='Load from inverse_suggest --json output')
    args = pa.parse_args()

    os.chdir(os.path.join(os.path.dirname(__file__), '..'))

    if args.from_json:
        print(f"Generating cases from {args.from_json}...")
        cases = generate_cases_from_inverse_design(
            args.from_json, args.out,
            ref_length_m=args.length, ref_height_m=args.height, ref_width_m=args.width,
        )
        print(f"\n{len(cases)} cases written to {args.out}/")
    else:
        print(f"Generating Ahmed body OpenFOAM cases for slants: {args.slants}")
        print(f"  L={args.length*1000:.0f}mm  H={args.height*1000:.0f}mm  "
              f"W={args.width*1000:.0f}mm  grnd={args.ground*1000:.0f}mm")
        print(f"  U∞={U_INF}m/s  Re={_re(args.length):.2e}")
        print()
        for slant in args.slants:
            case_dir = os.path.join(args.out, f'slant{slant:.0f}')
            generate_ahmed_case(
                case_dir=case_dir, length_m=args.length, height_m=args.height,
                width_m=args.width, slant_deg=slant, ground_clr=args.ground,
            )
            print(f"  slant={slant:.1f}°  → {case_dir}/")
        print(f"\nDone. To run: cd {args.out}/slant10 && ./Allrun")
        print("(Requires OpenFOAM loaded in environment)")
