"""
openfoam/drivaernet_case_generator.py

Generate OpenFOAM simpleFoam k-ω SST RANS cases for DrivAerNet car STL files.
Designed for parallel execution on Colab (8 CPU cores via MPI).

Physics
-------
  U∞   = 40 m/s    highway cruise speed
  Re   = U∞·L / ν  ≈ 1.2–1.5 × 10⁷  (full-scale car)
  Ma   = 40/343     ≈ 0.117           (incompressible)
  ρ    = 1.225 kg/m³
  ν    = 1.516e-5 m²/s

Boundary conditions
-------------------
  inlet   : fixedValue U=(40,0,0), turbulentIntensity k/omega
  outlet  : zeroGradient U, fixedValue p=0
  top     : slip (symmetry)
  sides   : slip (symmetry)
  ground  : movingWall U=(40,0,0)  — road moves at freestream speed
  car_body: noSlip U=(0,0,0)       — car+wheels treated as stationary solid

Usage
-----
    from openfoam.drivaernet_case_generator import generate_drivaernet_case
    generate_drivaernet_case(stl_path='path/to/car.stl',
                             geo=row_from_geometry_features_csv,
                             output_dir='of_cases/my_car')
"""

from __future__ import annotations

import json
import math
import os
import shutil

# ── Physical constants ────────────────────────────────────────────────────────
U_INF   = 40.0       # m/s
RHO     = 1.225      # kg/m³
NU      = 1.516e-5   # m²/s  kinematic viscosity air at 20°C
TI      = 0.05       # 5% turbulence intensity
N_PROCS = 8          # parallel cores for Colab


def _header(cls: str, location: str, obj: str) -> str:
    return f"""\
/*--------------------------------*- C++ -*----------------------------------*\\
| OpenFOAM DrivAerNet case — generated by ParaKoop/openfoam/drivaernet_case_generator.py |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    location    "{location}";
    object      {obj};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

"""


def _compute_domain(geo: dict) -> dict:
    """
    Compute OpenFOAM domain extents from DrivAerNet geometry parameters.
    All values in metres.
    """
    L = geo['length_mm'] / 1000.0
    H = geo['height_mm'] / 1000.0
    W = geo.get('width_mm', 2000.0) / 1000.0
    A = geo.get('frontal_area_mm2', W * H * 1e6) / 1e6   # m²

    # Domain: upstream 2L, downstream 5L, lateral ±4W, height 5H
    x_min = round(-2.0 * L, 3)
    x_max = round( 5.0 * L, 3)
    y_min = round(-4.0 * W, 3)
    y_max = round( 4.0 * W, 3)
    z_min = 0.0
    z_max = round( 5.0 * H, 3)

    Re = U_INF * L / NU
    k_inlet   = 1.5 * (U_INF * TI) ** 2
    om_inlet  = math.sqrt(k_inlet) / (0.09 ** 0.25 * 0.1 * H)

    # Background mesh cells — coarser than Ahmed body (car domain is much larger)
    nx = 180
    ny = 60
    nz = 40

    # locationInMesh: 2m upstream, slightly off-centre, mid-height
    loc_x = round(x_min + 0.5, 2)
    loc_y = 0.05
    loc_z = round(H * 0.5, 2)

    return dict(
        L=L, H=H, W=W, A=A, Re=Re,
        x_min=x_min, x_max=x_max,
        y_min=y_min, y_max=y_max,
        z_min=z_min, z_max=z_max,
        nx=nx, ny=ny, nz=nz,
        k_inlet=k_inlet, om_inlet=om_inlet,
        loc_x=loc_x, loc_y=loc_y, loc_z=loc_z,
    )


# ── Dictionary generators ────────────────────────────────────────────────────

def _block_mesh_dict(d: dict) -> str:
    return _header('dictionary', 'constant/polyMesh', 'blockMeshDict') + f"""\
scale 1.0;

vertices
(
    ({d['x_min']:.4f} {d['y_min']:.4f} {d['z_min']:.4f})  // 0
    ({d['x_max']:.4f} {d['y_min']:.4f} {d['z_min']:.4f})  // 1
    ({d['x_max']:.4f} {d['y_max']:.4f} {d['z_min']:.4f})  // 2
    ({d['x_min']:.4f} {d['y_max']:.4f} {d['z_min']:.4f})  // 3
    ({d['x_min']:.4f} {d['y_min']:.4f} {d['z_max']:.4f})  // 4
    ({d['x_max']:.4f} {d['y_min']:.4f} {d['z_max']:.4f})  // 5
    ({d['x_max']:.4f} {d['y_max']:.4f} {d['z_max']:.4f})  // 6
    ({d['x_min']:.4f} {d['y_max']:.4f} {d['z_max']:.4f})  // 7
);

blocks
(
    hex (0 1 2 3 4 5 6 7)
    ({d['nx']} {d['ny']} {d['nz']})
    simpleGrading (1 1 1)
);

boundary
(
    inlet   {{ type patch;    faces ((0 4 7 3)); }}
    outlet  {{ type patch;    faces ((1 2 6 5)); }}
    top     {{ type symmetry; faces ((4 5 6 7)); }}
    sides   {{ type symmetry; faces ((0 1 5 4) (3 7 6 2)); }}
    ground  {{ type wall;     faces ((0 3 2 1)); }}
);
"""


def _bc_U(d: dict) -> str:
    return _header('volVectorField', '0', 'U') + f"""\
dimensions [0 1 -1 0 0 0 0];
internalField uniform ({U_INF} 0 0);

boundaryField
{{
    inlet       {{ type fixedValue; value uniform ({U_INF} 0 0); }}
    outlet      {{ type zeroGradient; }}
    top         {{ type symmetry; }}
    sides       {{ type symmetry; }}
    ground          {{ type fixedValue; value uniform ({U_INF} 0 0); }}  // moving road
    "car_body_.*"   {{ type noSlip; }}
}}
"""


def _bc_p(d: dict) -> str:
    return _header('volScalarField', '0', 'p') + """\
dimensions [0 2 -2 0 0 0 0];
internalField uniform 0;

boundaryField
{
    inlet       { type zeroGradient; }
    outlet      { type fixedValue; value uniform 0; }
    top         { type symmetry; }
    sides       { type symmetry; }
    ground          { type zeroGradient; }
    "car_body_.*"   { type zeroGradient; }
}
"""


def _bc_k(d: dict) -> str:
    k = d['k_inlet']
    return _header('volScalarField', '0', 'k') + f"""\
dimensions [0 2 -2 0 0 0 0];
internalField uniform {k:.6f};

boundaryField
{{
    inlet       {{ type fixedValue; value uniform {k:.6f}; }}
    outlet      {{ type zeroGradient; }}
    top         {{ type symmetry; }}
    sides       {{ type symmetry; }}
    ground          {{ type kqRWallFunction; value uniform {k:.6f}; }}
    "car_body_.*"   {{ type kqRWallFunction; value uniform {k:.6f}; }}
}}
"""


def _bc_omega(d: dict) -> str:
    om = d['om_inlet']
    return _header('volScalarField', '0', 'omega') + f"""\
dimensions [0 0 -1 0 0 0 0];
internalField uniform {om:.4f};

boundaryField
{{
    inlet       {{ type fixedValue; value uniform {om:.4f}; }}
    outlet      {{ type zeroGradient; }}
    top         {{ type symmetry; }}
    sides       {{ type symmetry; }}
    ground          {{ type omegaWallFunction; value uniform {om:.4f}; }}
    "car_body_.*"   {{ type omegaWallFunction; value uniform {om:.4f}; }}
}}
"""


def _bc_nut(d: dict) -> str:
    return _header('volScalarField', '0', 'nut') + """\
dimensions [0 2 -1 0 0 0 0];
internalField uniform 0;

boundaryField
{
    inlet       { type calculated; value uniform 0; }
    outlet      { type calculated; value uniform 0; }
    top         { type symmetry; }
    sides       { type symmetry; }
    ground          { type nutkWallFunction; value uniform 0; }
    "car_body_.*"   { type nutkWallFunction; value uniform 0; }
}
"""


def _transport_props() -> str:
    return _header('dictionary', 'constant', 'transportProperties') + f"""\
transportModel  Newtonian;
nu              {NU};
"""


def _turbulence_props() -> str:
    return _header('dictionary', 'constant', 'turbulenceProperties') + """\
simulationType RAS;
RAS { RASModel kOmegaSST; turbulence on; printCoeffs on; }
"""


def _control_dict(d: dict, design_id: str) -> str:
    return _header('dictionary', 'system', 'controlDict') + f"""\
application     simpleFoam;
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         1000;
deltaT          1;
writeControl    timeStep;
writeInterval   100;
purgeWrite      3;
writeFormat     ascii;
writePrecision  8;
runTimeModifiable true;

functions
{{
    forceCoeffs
    {{
        type            forceCoeffs;
        libs            ("libforces.so");
        writeControl    timeStep;
        writeInterval   10;
        log             true;
        patches         ("car_body_.*");
        rho             rhoInf;
        rhoInf          {RHO};
        liftDir         (0 0 1);
        dragDir         (1 0 0);
        CofR            (0 0 0);
        pitchAxis       (0 1 0);
        magUInf         {U_INF};
        lRef            {d['L']:.4f};
        Aref            {d['A']:.6f};
    }}
}}
"""


def _fv_schemes() -> str:
    return _header('dictionary', 'system', 'fvSchemes') + """\
ddtSchemes    { default steadyState; }
gradSchemes   { default Gauss linear; }
divSchemes
{
    default         none;
    div(phi,U)      Gauss linearUpwind grad(U);
    div(phi,k)      Gauss upwind;
    div(phi,omega)  Gauss upwind;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}
laplacianSchemes { default Gauss linear corrected; }
interpolationSchemes { default linear; }
snGradSchemes    { default corrected; }
wallDist         { method meshWave; }
"""


def _fv_solution() -> str:
    return _header('dictionary', 'system', 'fvSolution') + """\
solvers
{
    p
    {
        solver          GAMG;
        smoother        GaussSeidel;
        tolerance       1e-7;
        relTol          0.01;
    }
    U  { solver smoothSolver; smoother GaussSeidel; tolerance 1e-8; relTol 0.1; }
    k  { solver smoothSolver; smoother GaussSeidel; tolerance 1e-8; relTol 0.1; }
    omega { solver smoothSolver; smoother GaussSeidel; tolerance 1e-8; relTol 0.1; }
}

SIMPLE
{
    nNonOrthogonalCorrectors 1;
    residualControl
    {
        p     1e-5;
        U     1e-5;
        k     1e-5;
        omega 1e-5;
    }
}

relaxationFactors
{
    fields  { p 0.3; }
    equations { U 0.7; k 0.7; omega 0.7; }
}
"""


def _snappy_dict(d: dict, stl_filename: str) -> str:
    # Wake refinement box just behind the car
    wake_x = round(d['L'] * 1.5, 2)
    box_min = f"(-0.2 {round(-d['W']*0.8, 2)} 0.0)"
    box_max = f"({wake_x}  {round( d['W']*0.8, 2)} {round(d['H']*1.2, 2)})"

    return _header('dictionary', 'system', 'snappyHexMeshDict') + f"""\
castellatedMesh true;
snap            true;
addLayers       true;

mergeTolerance  1e-6;

geometry
{{
    car_body
    {{
        type triSurfaceMesh;
        file "{stl_filename}";
    }}
    wakeBox
    {{
        type searchableBox;
        min  {box_min};
        max  {box_max};
    }}
}}

castellatedMeshControls
{{
    maxLocalCells        2000000;
    maxGlobalCells      10000000;
    minRefinementCells   10;
    nCellsBetweenLevels  3;
    features ( );

    refinementSurfaces
    {{
        car_body
        {{
            level (3 4);
            patchInfo {{ type wall; }}
        }}
    }}

    refinementRegions
    {{
        wakeBox  {{ mode inside;   levels ((1 1)); }}
        car_body {{ mode distance; levels ((0.1 3) (0.3 2) (0.8 1)); }}
    }}

    resolveFeatureAngle 30;
    locationInMesh ({d['loc_x']} {d['loc_y']} {d['loc_z']});
    allowFreeStandingZoneFaces true;
}}

snapControls
{{
    nSmoothPatch    3;
    tolerance       2.0;
    nSolveIter      30;
    nRelaxIter      5;
}}

addLayersControls
{{
    relativeSizes       true;
    layers
    {{
        "car_body_.*" {{ nSurfaceLayers 5; }}
        ground   {{ nSurfaceLayers 3; }}
    }}
    expansionRatio          1.2;
    finalLayerThickness     0.3;
    minThickness            0.1;
    nGrow                   0;
    featureAngle            60;
    nRelaxIter              3;
    nSmoothSurfaceNormals   1;
    nSmoothNormals          3;
    nSmoothThickness        10;
    maxFaceThicknessRatio   0.5;
    maxThicknessToMedialRatio 0.3;
    minMedialAxisAngle      90;
    nBufferCellsNoExtrude   0;
    nLayerIter              50;
}}

meshQualityControls
{{
    maxNonOrtho         65;
    maxBoundarySkewness 20;
    maxInternalSkewness 4;
    maxConcave          80;
    minFlatness         0.5;
    minVol              1e-13;
    minTetQuality       1e-30;
    minArea             -1;
    minTwist            0.02;
    minDeterminant      0.001;
    minFaceWeight       0.05;
    minVolRatio         0.01;
    minTriangleTwist    -1;
    nSmoothScale        4;
    errorReduction      0.75;
}}
"""


def _surface_feature_dict(stl_filename: str) -> str:
    return _header('dictionary', 'system', 'surfaceFeatureExtractDict') + f"""\
{stl_filename}
{{
    extractionMethod    extractFromSurface;
    extractFromSurfaceCoeffs {{ includedAngle 150; }}
    writeObj yes;
}}
"""


def _decompose_par_dict(n_procs: int) -> str:
    return _header('dictionary', 'system', 'decomposeParDict') + f"""\
numberOfSubdomains {n_procs};
method          scotch;
"""


def _allrun_script(design_id: str, stl_filename: str, n_procs: int) -> str:
    return f"""\
#!/bin/bash
# ParaKoop DrivAerNet validation case: {design_id}
# Geometry: {stl_filename}
# Solver  : simpleFoam k-ω SST  U∞={U_INF}m/s  {n_procs} procs

cd "$(dirname "$0")"

echo '[clean]'
find constant/polyMesh -maxdepth 1 -type f ! -name 'blockMeshDict' -delete 2>/dev/null; echo '  done'

echo '[blockMesh]'
blockMesh > log.blockMesh 2>&1 && echo '  done' || {{ tail -5 log.blockMesh; exit 1; }}

echo '[surfaceFeatureExtract]'
surfaceFeatureExtract > log.surfaceFeatureExtract 2>&1 && echo '  done' || {{ tail -5 log.surfaceFeatureExtract; exit 1; }}

echo '[snappyHexMesh]'
snappyHexMesh -overwrite > log.snappyHexMesh 2>&1 && echo '  done' || {{ tail -10 log.snappyHexMesh; exit 1; }}

echo '[decomposePar]'
decomposePar -force > log.decomposePar 2>&1 && echo '  done' || {{ tail -5 log.decomposePar; exit 1; }}

echo '[simpleFoam parallel ({n_procs} procs)]'
mpirun --allow-run-as-root -np {n_procs} simpleFoam -parallel > log.simpleFoam 2>&1 && echo '  done' || {{ tail -10 log.simpleFoam; exit 1; }}

echo '[reconstructPar]'
reconstructPar -latestTime > log.reconstructPar 2>&1 && echo '  done' || true

echo '[extract Cd/Cl]'
COEFF=$(find postProcessing -name 'coefficient.dat' -o -name 'forceCoeffs.dat' 2>/dev/null | head -1)
if [ -f "$COEFF" ]; then
    echo "  Found: $COEFF"
    grep -v '^#' "$COEFF" | tail -5
else
    echo '  WARNING: force coefficient file not found'
fi
echo "Case {design_id} complete."
"""


# ── Public API ────────────────────────────────────────────────────────────────

def generate_drivaernet_case(
    stl_path:   str,
    geo:        dict,
    output_dir: str,
    n_procs:    int = N_PROCS,
) -> str:
    """
    Generate a complete OpenFOAM simpleFoam case for a DrivAerNet car STL.

    Parameters
    ----------
    stl_path   : absolute path to the car STL file (can be 120MB+ full car)
    geo        : row from geometry_features.csv as dict
                 (keys: design_id, length_mm, width_mm, height_mm,
                        frontal_area_mm2, cd, ...)
    output_dir : directory to write the case (created if needed)
    n_procs    : CPU cores for parallel simpleFoam (default 8 for Colab)

    Returns
    -------
    output_dir path
    """
    os.makedirs(output_dir, exist_ok=True)

    design_id    = str(geo.get('design_id', os.path.basename(stl_path).replace('.stl', '')))
    stl_filename = design_id + '.stl'
    d            = _compute_domain(geo)

    # ── Directory structure ──────────────────────────────────────────────────
    for sub in ['0', 'constant/polyMesh', 'constant/triSurface', 'system']:
        os.makedirs(os.path.join(output_dir, sub), exist_ok=True)

    # ── Copy STL ─────────────────────────────────────────────────────────────
    dst_stl = os.path.join(output_dir, 'constant', 'triSurface', stl_filename)
    if not os.path.exists(dst_stl):
        print(f'  Copying STL ({os.path.getsize(stl_path)/1e6:.0f}MB)...', end=' ', flush=True)
        shutil.copy2(stl_path, dst_stl)
        print('done')

    # ── Write dictionaries ───────────────────────────────────────────────────
    files = {
        'constant/polyMesh/blockMeshDict': _block_mesh_dict(d),
        '0/U':   _bc_U(d),
        '0/p':   _bc_p(d),
        '0/k':   _bc_k(d),
        '0/omega': _bc_omega(d),
        '0/nut': _bc_nut(d),
        'constant/transportProperties': _transport_props(),
        'constant/turbulenceProperties': _turbulence_props(),
        'system/controlDict':              _control_dict(d, design_id),
        'system/fvSchemes':                _fv_schemes(),
        'system/fvSolution':               _fv_solution(),
        'system/snappyHexMeshDict':        _snappy_dict(d, stl_filename),
        'system/surfaceFeatureExtractDict': _surface_feature_dict(stl_filename),
        'system/decomposeParDict':         _decompose_par_dict(n_procs),
    }

    for rel_path, content in files.items():
        with open(os.path.join(output_dir, rel_path), 'w') as f:
            f.write(content)

    # ── Allrun script ────────────────────────────────────────────────────────
    allrun = os.path.join(output_dir, 'Allrun')
    with open(allrun, 'w') as f:
        f.write(_allrun_script(design_id, stl_filename, n_procs))
    os.chmod(allrun, 0o755)

    # ── Case metadata ────────────────────────────────────────────────────────
    meta = {
        'design_id':    design_id,
        'length_mm':    geo.get('length_mm'),
        'height_mm':    geo.get('height_mm'),
        'width_mm':     geo.get('width_mm'),
        'frontal_area_m2': d['A'],
        'rear_slant_deg':  geo.get('rear_slant_deg'),
        'cd_csv':       geo.get('cd'),
        'Re':           d['Re'],
        'U_inf_ms':     U_INF,
        'n_procs':      n_procs,
        'pk_cd_pred':   None,
        'pk_cl_pred':   None,
        'cfd_cd':       None,
        'cfd_cl':       None,
    }
    with open(os.path.join(output_dir, 'parakoop_case.json'), 'w') as f:
        json.dump(meta, f, indent=2)

    print(f'  Case ready: {output_dir}')
    print(f'    L={d["L"]:.2f}m  H={d["H"]:.2f}m  W={d["W"]:.2f}m  '
          f'A={d["A"]:.4f}m²  Re={d["Re"]:.2e}')
    print(f'    Domain: x[{d["x_min"]:.1f}, {d["x_max"]:.1f}]  '
          f'y[{d["y_min"]:.1f}, {d["y_max"]:.1f}]  z[0, {d["z_max"]:.1f}]')
    return output_dir


def generate_cases_from_csv(
    geometry_csv: str,
    stl_dir:      str,
    output_dir:   str,
    design_ids:   list[str] | None = None,
    n_cases:      int = 3,
    n_procs:      int = N_PROCS,
) -> list[str]:
    """
    Batch-generate cases from geometry_features.csv.
    Picks one representative per body style (fastback / notchback / estateback)
    unless design_ids are explicitly specified.
    """
    import pandas as pd

    df = pd.read_csv(geometry_csv)

    if design_ids:
        rows = df[df['design_id'].isin(design_ids)]
    else:
        # One median-Cd design per style
        rows = []
        for style_prefix in ['F_', 'N_', 'E_']:
            subset = df[df['design_id'].str.startswith(style_prefix)]
            if len(subset) == 0:
                subset = df[df['config'].str.startswith(style_prefix)]
            if len(subset) == 0:
                continue
            median_cd = subset['cd'].median()
            best = subset.iloc[(subset['cd'] - median_cd).abs().argsort()[:1]]
            rows.append(best.iloc[0])
        rows = pd.DataFrame(rows)

    case_dirs = []
    for _, row in rows.iterrows():
        geo = row.to_dict()
        did = geo['design_id']
        stl_path = os.path.join(stl_dir, did + '.stl')
        if not os.path.exists(stl_path):
            print(f'  SKIP {did}: STL not found at {stl_path}')
            continue
        case_dir = os.path.join(output_dir, did)
        generate_drivaernet_case(stl_path, geo, case_dir, n_procs=n_procs)
        case_dirs.append(case_dir)

    return case_dirs


if __name__ == '__main__':
    import argparse
    pa = argparse.ArgumentParser()
    pa.add_argument('--geo-csv', required=True)
    pa.add_argument('--stl-dir', required=True)
    pa.add_argument('--output-dir', default='openfoam/cases/drivaernet')
    pa.add_argument('--design-ids', nargs='+', default=None)
    pa.add_argument('--n-cases', type=int, default=3)
    pa.add_argument('--n-procs', type=int, default=N_PROCS)
    args = pa.parse_args()

    generate_cases_from_csv(
        geometry_csv=args.geo_csv,
        stl_dir=args.stl_dir,
        output_dir=args.output_dir,
        design_ids=args.design_ids,
        n_cases=args.n_cases,
        n_procs=args.n_procs,
    )
